FROM openjdk:8-jre

# Presto version will be passed in at build time
ARG PRESTO_VERSION=0.284

# Set the URL to download
ARG PRESTO_BIN=https://repo1.maven.org/maven2/com/facebook/presto/presto-server/${PRESTO_VERSION}/presto-server-${PRESTO_VERSION}.tar.gz

# Update the base image OS and install wget and python
RUN apt-get update && apt-get install -y wget python less

# Download Presto and unpack it to /opt/presto
RUN wget --quiet ${PRESTO_BIN} && \
    mkdir -p /opt && \
    tar -xf presto-server-${PRESTO_VERSION}.tar.gz -C /opt && \
    rm presto-server-${PRESTO_VERSION}.tar.gz && \
    ln -s /opt/presto-server-${PRESTO_VERSION} /opt/presto

# Specify the entrypoint to start
ENTRYPOINT /opt/presto/bin/launcher run
