column_mapping: dict = {
    "binanceTicker": {
        "eventType": "event_type",
        "eventTime": "event_time",
        "priceChange": "price_change",
        "priceChangePercent": "price_change_percent",
        "weightedAvgPrice": "weighted_avg_price",
        "firstTradePrice": "first_trade_price",
        "lastPrice": "last_price",
        "lastQuantity": "last_quantity",
        "bestBidPrice": "best_bid_price",
        "bestBidQuantity": "best_bid_quantity",
        "bestAskPrice": "best_ask_price",
        "openPrice": "open_price",
        "highPrice": "high_price",
        "lowPrice": "low_price",
        "totalTradedBaseAssetVolume": "total_traded_base_asset_volume",
        "totalTradedQuoteAssetVolume": "total_traded_quote_asset_volume",
        "statisticsOpenTime": "statistics_open_time",
        "statisticsCloseTime": "statistics_close_time",
        "firstTradeId": "first_trade_id",
        "lastTradeId": "last_trade_id",
        "totalNumberOfTrades": "total_number_of_trades",
    },
    "binanceBookTicker": {
        "updateId": "update_id",
        "bestBidPrice": "best_bid_price",
        "bestBidQuantity": "best_bid_quantity",
        "bestAskPrice": "best_ask_price",
        "bestAskQuantity": "best_ask_quantity",
    }
}
